### ISSUE TITLE
video-swiper 组件不支持在swiper-item下放置插槽

### ISSUE THREAD

**Issue by tianji2018** [wechat-miniprogram/miniprogram-component-plus#2]
video-swiper 组件不支持在swiper-item下放置插槽`<slot></slot>`

**Comment by wechat-miniprogram-admin** [comment]
有什么场景需要在 swiper-item 下放插槽么，如果只是想在对应视频画一些控件，根据当前的 activeId 改变下界面内容就可以了

**Comment by tianji2018** [comment]
> 有什么场景需要在 swiper-item 下放插槽么，如果只是想在对应视频画一些控件，根据当前的 activeId 改变下界面内容就可以了

比如在视频的上方放类似于抖音的按钮图标

**Comment by wechat-miniprogram-admin** [comment]
按钮图标这种直接在页面的wxml中加就可以了，可以覆盖在 video 上面的。如果想拿当前 video 的数据，可以根据 bindchange 拿 id
