### ISSUE TITLE
npm install失败

### ISSUE THREAD

**Issue by DroganC** [wechat-miniprogram/miniprogram-component-plus#6]
<img width="404" alt="WX20200529-112658@2x" src="https://user-images.githubusercontent.com/32896700/83217867-54097780-a19f-11ea-8346-87bb713c7513.png">

npm install失败

**Comment by DroganC** [comment]
pm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tencent%2ftslint-config-wxapp - Not found
npm ERR! 404 
npm ERR! 404  '@tencent/tslint-config-wxapp@0.0.2' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'miniprogram-component-plus-master'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chenlong/.npm/_logs/2020-05-29T03_25_24_157Z-debug.log

**Comment by trampboy** [comment]
是包 @tencent/tslint-config-wxapp 未找到，可以不需要，你可以去掉，再 npm install。如果你想找下 tslint-config-wxapp，可以参考下 weui-miniprogram 里的 [tslint-config-wxapp](https://github.com/wechat-miniprogram/weui-miniprogram/tree/master/tools/tslint-config-wxapp)

**Comment by Tidyzq** [comment]
已移除 @tencent/tslint-config-wxapp

**Comment by xianyu9527** [comment]
微信小程序自动化测试的时候,安装相关包还是会出现这个问题
